### ISSUE TITLE
Filter tests that run

### ISSUE THREAD

**Issue by SteveDesmond-ca** [ecoAPM/xunit.ts#51]
As a developer with a giant test suite, I want to only run a subset of tests, so that I don't need to wait as long to see results.

Acceptance criteria:
- user can add a CLI arg to filter tests that run based on a {regex? glob?} pattern

**Comment by amatyas001** [comment]
Many test frameworks tend to use the `only` chainable method to filter out specific test suites to run. This could be an option too. However, passing globs or filenames as CLI arguments also makes sense. Which one do you prefer?

**Comment by SteveDesmond-ca** [comment]
Looking at other xunit-style frameworks, here's the proposed spec:
- user can pass a `--filter` (`-f`) option followed by a string to match against the fully-qualified name of the test (`SuiteName.TestName`)
- if a filter is set, only run tests whose fully-qualified name contains the filter string
- numbers sent to reporters should total only based on the filtered set of tests, not all tests
- bonus 1 (separate PR): use regex instead of simple string matching
- bonus 2 (separate PR): allow multiple filters to be passed (as "or"s/unions, vs "and"s/intersects)

**Comment by SteveDesmond-ca** [comment]
Implemented in v1.1.0
